sudo: required
services:
  - docker

before_install:
  - docker build -t vladsereda/docker-k8s -f Dockerfile.dev .

script:
  - docker run -e CI=true vladsereda/docker-k8s npm run test -- --coverage --watchAll=false

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-k8s"
  env: "DockerK8s-env"
  bucket_name: elasticbeanstalk-us-east-1-912930353676
  bucket_path: "docker-k8s"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
